version: "3.9"

services:
  tokenizer:
    container_name: embedded-project-server
    restart: unless-stopped
    build: .
    ports:
      - 8080:8080
    environment:
      - ENV=development
      - PORT=8080
      - API_KEY=YWRtaW46YWRtaW4
 